#https://docs.aws.amazon.com/zh_cn/AWSCloudFormation/latest/UserGuide/quickref-ec2.html

Resources:
  ec2ForCloudformation:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: 
        { "Fn::Select": ["0", { "Fn::GetAZs": { "Ref": "AWS::Region" } }] }
      # AMI-ID
      ImageId: ami-00ae935ce6c2aa534
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SSHWEBSG

# Add elastic IP to EC2 instance
  mywebEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref ec2ForCloudformation

  # SSH + Web Security Group
  SSHWEBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and Web PORT
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0